apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: d55ff8okj-python
  janus-idp.io/tekton: d55ff8okj-python
  backstage.io/kubernetes-id: d55ff8okj-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: d55ff8okj-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
